
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    networks:
      - app-network

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  orders-service:
    build: ./services/orders-service
    container_name: orders-service
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
      - mongodb
    networks:
      - app-network
    environment:
      - ConnectionStrings__Default=Server=sqlserver;Database=OrdersDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true
      - MongoDb__ConnectionString=mongodb://mongodb:27017

  payments-service:
    build: ./services/payments-service
    container_name: payments-service
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/payments

networks:
  app-network:
    driver: bridge
